### ISSUE TITLE
[Cryogaia] Telecoms turret borked

### ISSUE THREAD

**Issue by gozulio** [Yawn-Wider/YWPolarisVore#333]
Turning off outer telecoms turrets don't actually turn the turrets off.

~~Telecoms cooling isn't set up correctly and the equipment overheats and burns out. (burned out equipment can be fixed with nanopaste!)~~ Edit: by Izac

**Comment by gozulio** [comment]
Updated with more specific information

**Comment by Repede** [comment]
Related to #338

**Comment by RadiantFlash7** [comment]
Cooling fixed, I need to know which sets of turrets need fixing?

**Comment by RadiantFlash7** [comment]
Eugh. I might need help with this a bit. I can't figure out how to make the turrets work properly.

**Comment by RadiantFlash7** [comment]
Turrets fixed I /think/. Needs another test.

**Comment by Repede** [comment]
Turrets still broke

**Comment by RadiantFlash7** [comment]
Still broke, still no progress. I’m banging my head on a wall with this.

**Comment by TheFurryFeline** [comment]
It's an access reading issue, probably. Check that bit out. If you're not s'posed to be in the area, like, don't have access_telecoms or whatever the var is in your job access list, it'll pew pew ya down.

**Comment by Shadow-Quill** [comment]
@TheFurryFeline Turrets aren't connecting to the control panel

**Comment by TheFurryFeline** [comment]
Probably an id var issue, then.

On Jan 9, 2020 18:45, "Shadow-Quill" <notifications@github.com> wrote:

@TheFurryFeline <https://github.com/TheFurryFeline> Turrets aren't
connecting to the control panel

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Yawn-Wider/YWPolarisVore/issues/333?email_source=notifications&email_token=AJGMTYZYORHVETZYQC4OQZDQ46ZKLA5CNFSM4J26NS6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEISF3LY#issuecomment-572808623>,
or unsubscribe

**Comment by RadiantFlash7** [comment]
Still never figured out what the hell the var was. ID's didn't link em together as far as I could tell. I'm lost.

**Comment by TheFurryFeline** [comment]
These turrets also shoot even the CD for some reason upstream. Post an issue to Virgo/Polaris

**Comment by RadiantFlash7** [comment]
@TheFurryFeline It's not an upstream issue afaik. it's that I haven't set up the turrets right. I just don't know how to fix this, unfortunately.
I always thought it was related to areas, but, I have no idea.
