### ISSUE TITLE
Bugged sec cart

### ISSUE THREAD

**Issue by SplinterGP** [Yawn-Wider/YWPolarisVore#465]
#### Brief description of the issue
Cant put keys back at sec cart

#### What you expected to happen
Put keys back into sec cart and vrooom vroom

#### What actually happened
Key no enter, vroom vroom not work

#### Steps to reproduce
- Get sec cart
- Take key out
- Try to put key back

#### Code Revision
- Server revision:  - 2020-01-15
117d09b1619344813f26148791473cf671116098 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
![image](https://user-images.githubusercontent.com/29824735/72495192-bec7a100-3804-11ea-9b10-69dc23d31751.png)

That's whats supposed to happen ^^^^

**Comment by TheFurryFeline** [comment]
So which type of vehicle is the issue here? What's the full name in-game?

**Comment by SplinterGP** [comment]
> So which type of vehicle is the issue here? What's the full name in-game?

It's the Sec Cart, it is able to pull a train trolley, much like the cargo one but for security, i'll see to find their code

**Comment by TheFurryFeline** [comment]
Couldn't find it myself, so it might be a renamed mapped item or something.

**Comment by Shadow-Quill** [comment]
> Couldn't find it myself, so it might be a renamed mapped item or something.

It's not mapped in, the name is something along the lines of `Security Cart`

**Comment by SplinterGP** [comment]
![image](https://user-images.githubusercontent.com/29824735/72672968-fec79780-3a41-11ea-8ec0-36a1a3f6e91b.png)

**Comment by RadiantFlash7** [comment]
I was going to say, It’s a subtype of the cargo tram and it’s in evidence storage

**Comment by TheFurryFeline** [comment]
Then as a subtype, it **should** work, reeee. Why are there so many
subtypes breaking regardless? >:c

On Jan 19, 2020 12:13, "RadiantFlash7" <notifications@github.com> wrote:

I was going to say, It’s a subtype of the cargo tram and it’s in evidence
storage

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Yawn-Wider/YWPolarisVore/issues/465?email_source=notifications&email_token=AJGMTYYM6HCM7KNE4XUJZATQ6SC2FA5CNFSM4KHOCG22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJKXIDI#issuecomment-576025613>,
or unsubscribe

**Comment by TheFurryFeline** [comment]
Also, wew. I see it's a _vr file that was made almost 4 years ago. Fancy that. https://github.com/Yawn-Wider/YWPolarisVore/commits/master/code/modules/vehicles/Securitrain_vr.dm

**Comment by TheFurryFeline** [comment]
Aha! I see the issue! `/obj/item/weapon/key/security` and `/obj/item/weapon/key/cargo_train`

**Comment by TheFurryFeline** [comment]
Fix works. PR'ing here.
