### ISSUE TITLE
Blueshield doesn't have access to engineering

### ISSUE THREAD

**Issue by Shadow-Quill** [Yawn-Wider/YWPolarisVore#494]
Can't get to CE's office

**Comment by RadiantFlash7** [comment]
This is a hold over from the old map, blueshields couldn’t enter engineering. Not sure if we want this changed or what.

**Comment by Shadow-Quill** [comment]
Pretty sure the BS should be able to reach all head offices

**Comment by benj8560** [comment]
wiki link says they should be able to but admin told me otherwise  I think the wiki just needs a update

**Comment by benj8560** [comment]
proly just to prevent power gaming and shit since that more or less makes you a nerfed CD having ALL of them

**Comment by Shadow-Quill** [comment]
You aren't supposed to have *all* access, just enough to reach your charges. (IE, BS would have no need for atmospherics/construction access, just engineering)

**Comment by RadiantFlash7** [comment]
Theres been debate over what access for the blueshield is sufficient. Preventing them from reaching inside every department was a hot topic for a while.

**Comment by SplinterGP** [comment]
Why not give the blueshield that thing that open doors on emergency and tells sec over radio ? i know emt has something like that

**Comment by TheFurryFeline** [comment]
The rescue hardsuit does indeed have a module for precisely that purpose, `		/obj/item/rig_module/pat_module,` being the rig module.

**Comment by Dopiotl** [comment]
So what, get the shield a "blueshield hardsuit" with that module? it'd make sense too, if he's going to be the babysitter of heads. To an extent

**Comment by TheFurryFeline** [comment]
Sounds logical. Don't forget to add the usual other modules like a suit
cooling unit, magboots, etc.

On Jan 21, 2020 08:59, "Dopiotl" <notifications@github.com> wrote:

So what, get the shield a "blueshield hardsuit" with that module? it'd make
sense too, if he's going to be the babysitter of heads. To an extent

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Yawn-Wider/YWPolarisVore/issues/494?email_source=notifications&email_token=AJGMTYZNEU3TEGTYGXLPSLDQ635S3A5CNFSM4KI7JRRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJP2M6Y#issuecomment-576693883>,
or unsubscribe

**Comment by Dwaggy** [comment]
I have mentioned this on several occasions, that engineering access is zero. which, in the huge map-change event, almost caused the CE to be killed due to me been unable to reach him without hacking in.

a RIG might be going a little too far for one module, if there was a way to make the module a self contained item, that might be a better way of going about it too. make it alert sec and command still as per P.A.T. But i feel a dedicated RIG for it all might be overkill. especually on this map where space and atmos venting isn't really an issue.

**Comment by Shadow-Quill** [comment]
I agree with Dwaggyhere. An item that could bypass access reqs would be helpful, especially if the head's in an area you won't have access to normally, anyways. (IE surgery or something)

**Comment by Hawk-v3** [comment]
I'd like it just because I personally have an EMT who can't wear an EMT RIG. I'd still like to be able to get to patients.

**Comment by izac112** [comment]
Must be some balance to it though seeing as with the rig you use power when you open the doors.

**Comment by Shadow-Quill** [comment]
Could just have it use a cell

**Comment by RadiantFlash7** [comment]
A dedicated rig is definitely overkill, Given it provides other benefits, such as holding broken bones in place to reduce pain/organs being damaged from them moving, etc... Especially since I just know blueshields will be slapping weaponry/ combat modules onto it. 

If I’m honest, I’d prefer they don’t have access to places, and simply have to shadow their assignment to enter places, but thats likely to far in the other direction.

**Comment by Dopiotl** [comment]
Suggestion : get the shield an actual hardsuit with that module, but it can't receive any other?
Just your all-access emergency hardsuit for babysitter duties. Un-upgradable. Heck, you can even force it to have a small power cell with limited amount of uses for it's module.
Doesn't event need to have a lot of resistances to much of any brute, energy, rads.
Make it paper-thin like the explo voidsuit for all I care

**Comment by KillianKirilenko** [comment]
Suit ponderings aside, access has been tackled pretty extensively in #692. If anyone finds problematic spots, create a new issue with screenshots of the location(s).
