### ISSUE TITLE
Snow walk sounds use tile/plating noises instead of snow.

### ISSUE THREAD

**Issue by RadiantFlash7** [Yawn-Wider/YWPolarisVore#500]
#### Brief description of the issue 
Snow walk sounds use tile/plating noises instead of snow.

#### What you expected to happen 
Snow sounds, damn it!

#### What actually happened
Tile sounds.

#### Steps to reproduce
- (Step 1)
- (Step 2)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
Litterally, if anyone could fix this, I'd appreciate it greatly.

**Comment by TheFurryFeline** [comment]
@Rykka-Stormheart, you worked with this sort of thing, right?

**Comment by Rykka-Stormheart** [comment]
> @Rykka-Stormheart, you worked with this sort of thing, right?

Yes, and the issue is tied to how footsteps were handled, last time I dug into it. I'd have to look again, but it's either the turf or the human_movement.dm. Granted Virgo has like sixteen different human.dm files .-.

**Comment by izac112** [comment]
@RadiantFlash7 did this ever get fixed?

**Comment by RadiantFlash7** [comment]
Nope. ;~;
I tried but it didn’t seem to fix it

**Comment by Rykka-Stormheart** [comment]
@RadiantFlash7 @izac112 Hey, just letting you know, @Darlantanis fixed this downstream.

https://github.com/CHOMPStation2/CHOMPStation2/pull/285

**Comment by Darlantanis** [comment]
I got poked to share some info on how to fix this so I'll give a short summary. The problem is flooring.dm. When New() is called (i.e. the proc that gets called when atoms are generated), flooring.dm has a line reading "footstep_sounds = base_footstep_sounds" which overrides anything set for "footstep_sounds" elsewhere in the code. That's why everything sounds like metal.

To easily get around this issue, you need to modify New(), call super, then set footstep_sounds to the desired audio files. You can reference my PR mentioned above for specific examples. It'll follow a format like:
tilefilepath/New()
     ..()
     footstep_sounds = list

Note that this (probably) only applies to base tiles. Anything coded as decal flooring (e.g. wood flooring, carpeting, shovel-able snow) just needs footstep_sounds set to the desired audio files and it will work as expected. I'm unfamiliar with your map but you may consider using decal-type snow if you'd like players to be able to dig it up and uncover the dirt/stone/ice/etc. underneath. Polaris' snow code is good to reference if you're uncertain how to achieve this.

**Comment by RadiantFlash7** [comment]
@Darlantanis Originally I went with decal flooring, but the main issue with it was the planetary turfs needed for cryogaia didn't seem to work properly with it.
I really appreciate the help on fixing this issue though.

**Comment by izac112** [comment]
Apprantly fixed comment if not
