### ISSUE TITLE
Security Jacket Buttons

### ISSUE THREAD

**Issue by Legion2552** [Yawn-Wider/YWPolarisVore#597]
#### Brief description of the issue
The Security Jackets unbutton-button is broken.

#### What you expected to happen
The jacket to change to a buttoned and unbuttoned sprite when the verb 'Toggle-Coat-Buttons' is used.

#### What actually happened
The message "You unbutton the coat." shows up. But then the Jacket disappears. The Sprite does not change, and it would appear that the unbuttons sprite is the natural 'buttoned' state of the jacket.

#### Steps to reproduce
- Click 'Toggle-Coat-Buttons' verb while wearing the Security Jacket.
- It breaks.
- ???
- Profit

#### Code Revision
- Server revision:  - 2020-02-19
641b8eddd536e71fabb181caffd552e2a7f68adb 
 
#### Anything else you may wish to add:
- Nah. That's pretty much it.

**Comment by KillianKirilenko** [comment]
When opened, the icon_state changes to `icon_state = "secjacket_open_open"`, because the original coder decided the default state should be `icon_state = "secjacket_open"` but didn't change the default `open` var value should be 1. Oops?

Observing/fixing this with VV has also revealed that the `item_state` value isn't changed when the buttons are toggled, only the `icon_state`, which means that the onmob sprite doesn't change at all. This is probably made more of an issue by the choice to store the object sprites in the same file as the onmob sprites.

This thing's two/three different kinds of broke.

**Comment by RadiantFlash7** [comment]
>..>
I may, have possibly half did the job in the middle of another project way back when, and forgot to go back and finish fixing the jacket code.
