### ISSUE TITLE
the surface mining room's airlock is all access

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#656]
#### Brief description of the issue
the surface mining room's airlock is all access
the mining gear has strangely special lockers with no lock but with mining gear in it including KA's

it allowed a baldie to powergame and steal one as an intern and parade around in full mining gear

#### What you expected to happen
for the mining airlock to have mining access restrictions

#### What actually happened
the baldie was equipped with a KA by just walking in like a good powergamer

**Comment by benj8560** [comment]
also sec outpost has kinda a useless airlock if you leave it open outwards you can just walk in and use the airlock controller to open ether door. Not a big deal since you are not getting much further without hacking or breaking something but it does get you past the first door. At least the buttons have ID locks but not the controller
