### ISSUE TITLE
Camera Issues Megathread

### ISSUE THREAD

**Issue by KillianKirilenko** [Yawn-Wider/YWPolarisVore#751]
Once #744 is merged I'm going to start looking into fixing security cameras across the station.

If you know of any spots with major issues (either lack of coverage, duplicates, wrong network, wrong name, etc.) add a comment to this issue with as much information as possible.

At the very least I need the location, preferably via screenshot of the camera and a few surrounding tiles. [IrfanView](https://www.irfanview.com/) is great for this (just printscreen, paste into irfanview, select the area you want to cut out, ctrl-c, then ctrl-v whilst writing a comment), as is [gyazo](https://gyazo.com/).

**Comment by benj8560** [comment]
expect me to start dumping a bunch of shit here next time I am on as AI proly tomorrow night maybe

**Comment by Laria-D2** [comment]
--- Telecommunications---
Telecommunications cameras are hooked up to a nonexistent tcomms network rather than the proper Telecommunications label. No screenshot needed it's all of telecommunications, the motion alarm camera on the left of the first room works.. But it's the only alarm camera in the whole area.
--- Civilian---
Visitor room Hall AP, aka dorms hallway both left and right hall cameras have the same name.

One Visitor Dining should just be renamed Arrivals, the Visitor Dining near dorms isn't properly attached to the wall.

Libaray Fore, One is actually the bartender's backroom and needs to be renamed to reflect that.

--- Engineering---
Atmospherics Hallway, One camera is actually the workshop located just above the cargo tug by the CE office.

Engineering Exit Port is missing a light.

Medical Substation, the second one is actually in Atmospherics over the tanks.

Toxins Substation (1) is Engineering Lobby. Toxins Substation (2) is Lower Engineering Hallway south by the spare canisters and apc. (3rd is as intended)
--- Exploration---
There are two Exploration Hanger Aft's, they need name separation, Same with Fore... And the Meeting Room.

---Medical---
Medbay EMT office is facing the wrong way and Redundant as medbay EMT bay is properly installed

Medbay Exam Room is Virology Entrance (airlock)

Medbay Lower hallway Starboard needs a light.

Medbay Psychiatrists Office needs moved as it has a blind spot in the top right corner of the room.

Medbay Recovery Ward is Medical EMT Equipment Storage

Medbay break room (1) is Operation Observation Room

Surgery Observation 2 is a redundant camera covered above.

Surgery Wing Starboard is Virology lab (south end of the north room)

Virology Entry is the entry Lobby not the airlock.

Virology lab (1) is in Patient room A. Virology Lab (2) is the leftmost camera.

Medbay Reception has a numbered Camera for behind the desk.

Operating Theatre 1 and 2 have redundant cameras with numbers.

--There are No Outside Cameras---

---Research---
* These should be moved to Research Outpost since they're on the lowest level.
Research - Miscellaneous Test Chamber (1) is Phoro chemistry test chamber.

*Research Hall Aft (2) is Research - Toxins Test Chamber West

*Research - Toxins Test Chamber (North and South)

*All Xeno, Toxins and Lower Hallway Cameras

*There are (3) Research Lower Hallway cameras with no way to tell them apart, each covers a different lower hallway (1) is Xenoflora entrance (2) is Toxins Research Entrance (3) is by the elevator and thus could double as mining/be added to mining.

Both left and right entries to research are named Research Port Entry (1) is left and (2) is right.

Secure Xenobiology aft (1) is South Robotics near the robot chargers.

Xenobiology Control Room (1) is Right research Hallway beside the RD office and Research Storage

Xenobiology Surgery (1) is Research Hallway South of RD office. Xeno Biology Surgery (2) is *Xenobiology Storage (3 is as intended)

---Research Outpost---
OPR - Expedition Airlock (1) is Security Airlock OPR - Expedition Airlock 2 is Mining (logging) Airlock OPR - Expedition Airlock (3) is Public Teleporters Airlock

---Research Outpost---
Research Outpost Gas Heating #607 is facing the wrong way.

Workshop #796 is facing the wrong way.

---Prison---
Prison Visitation (1) is Brig Cell 2

Prison Dormitories and SEC- Brig Bedroom are redundant to each other (one tile apart)

---Security---
Camera #3707 #4807 #5321 #5470 #7928, #9338 don't exist and are inside the locker in the hidden PI room Right of the pool showers, opening that wooden locker reveals no cameras so this has to be bugged code.

Prison Court (1) is Security - Locker Room and Prison Court (2) should be Moved to Prison.

Prison Disposal Processing is Secure Evidence Storage.
------
Those are all the ones I've noted so far. I didn't feel like doing screenshots but this should be more than enough information to dig through them in game and fix them.

**Comment by KillianKirilenko** [comment]
Excellent, thank you.

For outside cameras, I suspect they weren't set up due to potential power issues. I've been contemplating how best to tackle this. It may either require new objects (essentially, cameras mounted on poles) that have special power rules, or something else.

As for the numbered cameras on Security's net; they're not bugged. It took me a while to figure them out, but they're legit.

**Comment by Laria-D2** [comment]
But cameras don't use power... I set up cameras (in game) outside myself often, especially around windows and link them to the Outside network.

**Comment by KillianKirilenko** [comment]
A little counterintuitive, but fair enough. That makes my life a lot easier. I'll see what I can rig up.

**Comment by Laria-D2** [comment]
Well it does make sense, why else would you be able to click the 'power alarms' section if cameras didn't work in unpowered sections, they seem like a low power system that can be run off of data cables only anyway.

**Comment by benj8560** [comment]
arighty I'm just gonna be dumping screen-caps here from AI since I am lazy any areas you somehow can't ID just lemme know. Most of these spots are not super big deals but can be annoying when someone walks directly up to a door and asks you to open it I often end up not being able to track sometimes in a lot of these spots or not even being able to see the dang door.


![dreamseeker_p2HL2qI66L](https://user-images.githubusercontent.com/26511091/83317281-729c5c80-a1f9-11ea-9074-25ef9899f868.png)

![dreamseeker_sk7jeG3HIf](https://user-images.githubusercontent.com/26511091/83317282-762fe380-a1f9-11ea-86fc-e57d09ca6a00.png)

![dreamseeker_jUK8vLtBdM](https://user-images.githubusercontent.com/26511091/83317286-792ad400-a1f9-11ea-8c9d-031734f7a477.png)

![dreamseeker_ZmgNcG9Ehg](https://user-images.githubusercontent.com/26511091/83317288-7d56f180-a1f9-11ea-85ee-72ed29073114.png)

![dreamseeker_u0sieU0moH](https://user-images.githubusercontent.com/26511091/83317290-7f20b500-a1f9-11ea-97e2-e96d63bbff1f.png)

![dreamseeker_iUNCRAdeYy](https://user-images.githubusercontent.com/26511091/83317294-81830f00-a1f9-11ea-93c4-38d0e9694f0a.png)

![dreamseeker_C3k2cBAs4L](https://user-images.githubusercontent.com/26511091/83317300-86e05980-a1f9-11ea-88a7-88f45edb0c23.png)

![dreamseeker_ihJBCc9BCE](https://user-images.githubusercontent.com/26511091/83317318-ab3c3600-a1f9-11ea-9c2a-6d294916f1a1.png)

(this is a big one no idea why we don't have a cam there)     ![dreamseeker_DURoYWjDro](https://user-images.githubusercontent.com/26511091/83317321-ad9e9000-a1f9-11ea-93d8-133d5cb0fdc9.png)

![dreamseeker_TweckqeLrZ](https://user-images.githubusercontent.com/26511091/83317338-c5761400-a1f9-11ea-8cbb-9b5725c09313.png)

![dreamseeker_kqbP49KUeR](https://user-images.githubusercontent.com/26511091/83317339-c7d86e00-a1f9-11ea-88fc-7747e686a647.png)
