### ISSUE TITLE
Fryer temps

### ISSUE THREAD

**Issue by Armyguy** [Yawn-Wider/YWPolarisVore#908]
#### Brief description of the issue
The Deep Fryers max temp is 400C

#### What you expected to happen
To not be Deep frying at 750F

#### What actually happened
I was  frying at 750F

#### Steps to reproduce
- (Step 1)Look at the Deep Fryers

#### Code Revision
- B:master D:2020-07-27
 
#### Anything else you may wish to add:
- Just setting it to 200C fixs this.

**Comment by KillianKirilenko** [comment]
Asked the person handling the port of the cooking upstream, "functioning as intended".

**Comment by SplinterGP** [comment]
So its meant to reach 400c?

**Comment by KillianKirilenko** [comment]
> Nyria: I'm handling it, ya, the intent was just that fryers have a higher temperature than ovens/etc. :p
Nyria: I didn't really put any thought into the exact math
Killian: fair enough
Nyria: which can be heated to almost 500° F)
Nyria: If we're being ~absolutely realistic~ I could probably reduce the temperature, yes
Nyria: but as it is all it is is an arbitrary number for the purposes of how long it takes to heat and what the optimal temp is
Killian: if we were being absolutely realistic nobody would play chef because it would take most of a round to prepare food and then cook it :popcorn:
Nyria: :p
Nyria: so ya, the number issue isn't really a problem, it was more meant to be "fryer hotter than oven and grill"
