### ISSUE TITLE
Weird Bug: Security Shuttle Edition

### ISSUE THREAD

**Issue by LordPapalus** [Yawn-Wider/YWPolarisVore#971]
**Brief description of the issue**
I took the Security shuttle for a flight and selected the "Borealis Majoris Navpoint" which is basically the outside snowy area and the atmospherics on the shuttle got changed to those outside

**What you expected to happen**
Shuttle not being fucked over by snow planet Atmos

**What actually happened**
Shuttle Atmos got changed to that of the outside

**Steps to reproduce**
- Get on Sec Shuttle
- Go to the Borealis Majoris Navpoint
- Freeze to death

**Code Revision**
_Server revision: B:-Using TGS- D:-Using TGS-
Commit: 7bd46096eca46f6c0fb333c8e15ba48629c78df5
TGS version: /tg/station 13 Server v3.2.6.3
DMAPI version: 3.2.1.0_ 
 
**Anything else you may wish to add:**
Please fix this

**Comment by LordPapalus** [comment]
And while I'm here, Warden's office doesn't have it's own air alarm
plz fix Izac kthank

**Comment by Laria-D2** [comment]
Since the air alarm was mentioned the sec hallway outside of the warden office, armory, sec lockers, main meeting areas, ect, basically a very important hallway with stairs leading to the prison which can get gas leaks on occasion doesn't have an air alarm meaning those vents can't be controlled and a gas leak in that area goes unregistered.

**Comment by izac112** [comment]
Make separate issue for the air alarms, the one in the warden has been fixed in the latest pr though
